config/routes.rb
RailsDevise::Application.routes.draw do
  resources :subscriptions

  resources :nugget_types

  resources :vimeo_embeds

  resources :youtube_embeds

  root :to => "home#index"
  devise_for :users, :controllers => {:registrations => "registrations"}
  match "courses/browse", :to=> "courses#browse", :via=>:get
  match "courses/teach", :to=> "courses#teach", :via=>:get
  match "/users/show", :to=> "home#show", :via=>:get
  match "/users/update",:to=> "users#update",:via=>:post
  #match "/subscriptions/user",:to=> "subscriptions#user_subscriptions",:via=>:get
  resources :users
  resources :nuggets
  resources :courses do
    member do
      get 'view'
      get 'subscribe'
    end
  end

end

app/models/youtube_embed.rb
class YoutubeEmbed < ActiveRecord::Base
end

app/controllers/youtube_embeds_controller.rb
class YoutubeEmbedsController < ApplicationController
  before_action :set_youtube_embed, only: [:show, :edit, :update, :destroy]
  before_action :confirm_logged_in

  # GET /youtube_embeds
  # GET /youtube_embeds.json
  def index
    @youtube_embeds = YoutubeEmbed.all
  end

  # GET /youtube_embeds/1
  # GET /youtube_embeds/1.json
  def show
  end

  # GET /youtube_embeds/new
  def new
    @youtube_embed = YoutubeEmbed.new
  end

  # GET /youtube_embeds/1/edit
  def edit
  end

  # POST /youtube_embeds
  # POST /youtube_embeds.json
  def create
    @youtube_embed = YoutubeEmbed.new(youtube_embed_params)

    respond_to do |format|
      if @youtube_embed.save
        format.html { redirect_to @youtube_embed, notice: 'Youtube embed was successfully created.' }
        format.json { render :show, status: :created, location: @youtube_embed }
      else
        format.html { render :new }
        format.json { render json: @youtube_embed.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /youtube_embeds/1
  # PATCH/PUT /youtube_embeds/1.json
  def update
    respond_to do |format|
      if @youtube_embed.update(youtube_embed_params)
        format.html { redirect_to @youtube_embed, notice: 'Youtube embed was successfully updated.' }
        format.json { render :show, status: :ok, location: @youtube_embed }
      else
        format.html { render :edit }
        format.json { render json: @youtube_embed.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /youtube_embeds/1
  # DELETE /youtube_embeds/1.json
  def destroy
    @youtube_embed.destroy
    respond_to do |format|
      format.html { redirect_to youtube_embeds_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_youtube_embed
      @youtube_embed = YoutubeEmbed.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def youtube_embed_params
      params.require(:youtube_embed).permit(:youtube_id, :nugget_id)
    end

    def set_nugget
      if params[:nugget_id]
        @course = Course.find(params[:nugget_id])
      elsif params[:youtube_embed][:nugget_id]
        @course = Course.find(params[:youtube_embed][:nugget_id])
      else
        puts "Could not find course_id"
      end
    end
end

app/helpers/youtube_embeds_helper.rb
module YoutubeEmbedsHelper
end

app/views/youtube_embeds/_form.html.erb
<%= simple_form_for @youtube_embed, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :youtube_id %>
  <%= f.input :nugget_id %>
  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                youtube_embeds_path, :class => 'btn' %>
  </div>
<% end %>

app/views/youtube_embeds/edit.html.erb
<%- model_class = YoutubeEmbed -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/youtube_embeds/index.html.erb
<%- model_class = YoutubeEmbed -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:youtube_id) %></th>
      <th><%= model_class.human_attribute_name(:nugget_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @youtube_embeds.each do |youtube_embed| %>
      <tr>
        <td><%= link_to youtube_embed.id, youtube_embed_path(youtube_embed) %></td>
        <td><%= youtube_embed.youtube_id %></td>
        <td><%= youtube_embed.nugget_id %></td>
        <td><%=l youtube_embed.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_youtube_embed_path(youtube_embed), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      youtube_embed_path(youtube_embed),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_youtube_embed_path,
            :class => 'btn btn-primary' %>

app/views/youtube_embeds/new.html.erb
<%- model_class = YoutubeEmbed -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/youtube_embeds/show.html.erb
<%- model_class = YoutubeEmbed -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:youtube_id) %>:</strong></dt>
  <dd><%= @youtube_embed.youtube_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:nugget_id) %>:</strong></dt>
  <dd><%= @youtube_embed.nugget_id %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              youtube_embeds_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_youtube_embed_path(@youtube_embed), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              youtube_embed_path(@youtube_embed),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>