config/routes.rb
RailsDevise::Application.routes.draw do
  resources :subscriptions

  resources :nugget_types

  resources :vimeo_embeds

  resources :youtube_embeds

  root :to => "home#index"
  devise_for :users, :controllers => {:registrations => "registrations"}
  match "courses/browse", :to=> "courses#browse", :via=>:get
  match "courses/teach", :to=> "courses#teach", :via=>:get
  match "/users/show", :to=> "home#show", :via=>:get
  match "/users/update",:to=> "users#update",:via=>:post
  #match "/subscriptions/user",:to=> "subscriptions#user_subscriptions",:via=>:get
  resources :users
  resources :nuggets
  resources :courses do
    member do
      get 'view'
      get 'subscribe'
    end
  end

end

app/controllers/nugget_types_controller.rb
class NuggetTypesController < ApplicationController
  before_action :set_nugget_type, only: [:show, :edit, :update, :destroy]

  # GET /nugget_types
  # GET /nugget_types.json
  def index
    @nugget_types = NuggetType.all
  end

  # GET /nugget_types/1
  # GET /nugget_types/1.json
  def show
  end

  # GET /nugget_types/new
  def new
    @nugget_type = NuggetType.new
  end

  # GET /nugget_types/1/edit
  def edit
  end

  # POST /nugget_types
  # POST /nugget_types.json
  def create
    @nugget_type = NuggetType.new(nugget_type_params)

    respond_to do |format|
      if @nugget_type.save
        format.html { redirect_to @nugget_type, notice: 'Nugget type was successfully created.' }
        format.json { render :show, status: :created, location: @nugget_type }
      else
        format.html { render :new }
        format.json { render json: @nugget_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /nugget_types/1
  # PATCH/PUT /nugget_types/1.json
  def update
    respond_to do |format|
      if @nugget_type.update(nugget_type_params)
        format.html { redirect_to @nugget_type, notice: 'Nugget type was successfully updated.' }
        format.json { render :show, status: :ok, location: @nugget_type }
      else
        format.html { render :edit }
        format.json { render json: @nugget_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /nugget_types/1
  # DELETE /nugget_types/1.json
  def destroy
    @nugget_type.destroy
    respond_to do |format|
      format.html { redirect_to nugget_types_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_nugget_type
      @nugget_type = NuggetType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def nugget_type_params
      params.require(:nugget_type).permit(:name)
    end
end

app/helpers/nugget_types_helper.rb
module NuggetTypesHelper
end

app/views/nugget_types/_form.html.erb
<%= simple_form_for(@nugget_type) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/nugget_types/edit.html.erb
<h1>Editing nugget_type</h1>

<%= render 'form' %>

<%= link_to 'Show', @nugget_type %> |
<%= link_to 'Back', nugget_types_path %>

app/views/nugget_types/index.html.erb
<h1>Listing nugget_types</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @nugget_types.each do |nugget_type| %>
      <tr>
        <td><%= nugget_type.name %></td>
        <td><%= link_to 'Show', nugget_type %></td>
        <td><%= link_to 'Edit', edit_nugget_type_path(nugget_type) %></td>
        <td><%= link_to 'Destroy', nugget_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Nugget type', new_nugget_type_path %>

app/views/nugget_types/new.html.erb
<h1>New nugget_type</h1>

<%= render 'form' %>

<%= link_to 'Back', nugget_types_path %>

app/views/nugget_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @nugget_type.name %>
</p>

<%= link_to 'Edit', edit_nugget_type_path(@nugget_type) %> |
<%= link_to 'Back', nugget_types_path %>