config/routes.rb
RailsDevise::Application.routes.draw do
  resources :subscriptions

  resources :nugget_types

  resources :vimeo_embeds

  resources :youtube_embeds

  root :to => "home#index"
  devise_for :users, :controllers => {:registrations => "registrations"}
  match "courses/browse", :to=> "courses#browse", :via=>:get
  match "courses/teach", :to=> "courses#teach", :via=>:get
  match "/users/show", :to=> "home#show", :via=>:get
  match "/users/update",:to=> "users#update",:via=>:post
  #match "/subscriptions/user",:to=> "subscriptions#user_subscriptions",:via=>:get
  resources :users
  resources :nuggets
  resources :courses do
    member do
      get 'view'
      get 'subscribe'
    end
  end

end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
 	validates :course_id, :uniqueness => {:scope => :user_id}
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_action :confirm_logged_in
  before_action :set_subscription, only: [:show, :edit, :update, :destroy]
  before_action :find_user

  # GET /subscriptions
  # GET /subscriptions.json
  def index
    @user_subscriptions = Subscription.where(:user_id=>@user.id).distinct
    @courses = Array.new
    @user_subscriptions.each do |subscription|
      @cur_course_id = subscription.course_id
      @cur_course = Course.find(@cur_course_id)
      @courses.push(@cur_course)
    end
  end

  # GET /subscriptions/1
  # GET /subscriptions/1.json
  
  def show
  end

  #GET /subscriptions/user

  #def user_subscriptions
  #  @user = User.find(current_user.id)
  #  @user_subscriptions = @user.subscriptions.latest_updated
  #end


  # GET /subscriptions/new
  def new
    @subscription = Subscription.new
  end

  # GET /subscriptions/1/edit
  def edit
  end

  # POST /subscriptions
  # POST /subscriptions.json
  def create
    @subscription = Subscription.new(subscription_params)

    respond_to do |format|
      if @subscription.save
        format.html { redirect_to @subscription, notice: 'Subscription was successfully created.' }
        format.json { render :show, status: :created, location: @subscription }
      else
        format.html { render :new }
        format.json { render json: @subscription.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subscriptions/1
  # PATCH/PUT /subscriptions/1.json
  def update
    respond_to do |format|
      if @subscription.update(subscription_params)
        format.html { redirect_to @subscription, notice: 'Subscription was successfully updated.' }
        format.json { render :show, status: :ok, location: @subscription }
      else
        format.html { render :edit }
        format.json { render json: @subscription.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subscriptions/1
  # DELETE /subscriptions/1.json
  def destroy
    @subscription.destroy
    respond_to do |format|
      format.html { redirect_to subscriptions_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subscription
      @subscription = Subscription.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subscription_params
      params.require(:subscription).permit(:user_id, :course_id)
    end

    def find_user
      @user = User.find(current_user.id)
    end
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/subscriptions/_form.html.erb
<%= simple_form_for(@subscription) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :user_id %>
    <%= f.input :course_id %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/subscriptions/edit.html.erb
<h1>Editing subscription</h1>

<%= render 'form' %>

<%= link_to 'Show', @subscription %> |
<%= link_to 'Back', subscriptions_path %>

app/views/subscriptions/index.html.erb
<h1>Listing subscriptions</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Course</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <!--tbody>

    <% @user_subscriptions.each do |subscription| %>
      <tr>
        <td><%= subscription.user_id %></td>
        <td><%= subscription.course_id %></td>
        <td><%= link_to 'Show', subscription %></td>
        <td><%= link_to 'Edit', edit_subscription_path(subscription) %></td>
        <td><%= link_to 'Destroy', subscription, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody-->
</table>

<% @courses.zip(@user_subscriptions).each do |course,subscription| %>
    <div class="col-sm-6 col-md-3">
      <div class="thumbnail">
        <%= image_tag course.avatar.url(:medium), :height=>160,:width=>200 %>
        <div class="caption">
          <h3><%= course.name %></h3>
          <p><%= course.description %></p>
          <p>
          <%= link_to("View Course", view_course_path(course), :class => 'btn btn-primary') %>
          <%= link_to 'Unsubcribe', subscription, method: :delete, :class => 'btn btn-primary',data: { confirm: 'Are you sure?' } %>
          </p>

        </div>
      </div>
    </div>
<% end %>


<br>

<!--%= link_to 'New Subscription', new_subscription_path %-->

app/views/subscriptions/new.html.erb
<h1>New subscription</h1>

<%= render 'form' %>

<%= link_to 'Back', subscriptions_path %>

app/views/subscriptions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @subscription.user_id %>
</p>

<p>
  <strong>Course:</strong>
  <%= @subscription.course_id %>
</p>

<%= link_to 'Edit', edit_subscription_path(@subscription) %> |
<%= link_to 'Back', subscriptions_path %>