config/routes.rb
RailsDevise::Application.routes.draw do
  resources :subscriptions

  resources :nugget_types

  resources :vimeo_embeds

  resources :youtube_embeds

  root :to => "home#index"
  devise_for :users, :controllers => {:registrations => "registrations"}
  match "courses/browse", :to=> "courses#browse", :via=>:get
  match "courses/teach", :to=> "courses#teach", :via=>:get
  match "/users/show", :to=> "home#show", :via=>:get
  match "/users/update",:to=> "users#update",:via=>:post
  #match "/subscriptions/user",:to=> "subscriptions#user_subscriptions",:via=>:get
  resources :users
  resources :nuggets
  resources :courses do
    member do
      get 'view'
      get 'subscribe'
    end
  end

end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Know Infinite', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <% if user_signed_in? %>
          <li class="dropdown" data-no-turbolink>
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Teach<b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><%= link_to 'My Courses', courses_path %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to 'Teach', courses_teach_path %></li>
        <% end %>
        <% if user_signed_in? %>
        <li class="dropdown" data-no-turbolink>
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Learn<b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><%= link_to 'All Courses', courses_browse_path %></li>
              <li><%= link_to 'My Subscriptions', "/subscriptions" %></li>
            </ul>
        </li>
        <%else%>
        <li><%= link_to 'Learn', courses_browse_path %></li>
        <% end %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <%= render 'layouts/navigation_links_right' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Logout', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Login', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>
<% if user_signed_in? %>
  <li><%= link_to 'Users', users_path %></li>
<% end %>

app/views/layouts/_navigation_links_right.html.erb
<%# add navigation links to this file %>
<% if user_signed_in? %>
	<li class="dropdown" data-no-turbolink>
	  <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.name %><b class="caret"></b></a>
	  <ul class="dropdown-menu">
	    <li><%= link_to 'Edit account', edit_user_registration_path %></li>
	    <li><%= link_to 'Logout', destroy_user_session_path, :method=>'delete' %></li>
	  </ul>
	</li>
<% else %>
  	<li><%= link_to 'Login', new_user_session_path %></li>
  	<li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Know Infinite" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Rails Devise" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main" class="container">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>